version: '3.7'

services:
  terraform:
    user: 1000:1000
    image: datagov-ssb/terraform:latest
    build:
      context: .
    volumes:
      - .:/code
    working_dir: /code
    environment:
      # Terraform backend bucket creds
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      
      # Secrets for the appropriate Terraform workspace
      - TF_VAR_aws_access_key_id
      - TF_VAR_aws_secret_access_key
      - TF_VAR_cf_username
      - TF_VAR_cf_password
      - TF_LOG=info
      - TF_LOG_PATH=terraform.log
