version: '3.7'

services:
  terraform:
    image: datagov-ssb/terraform:latest
    build:
      context: .
    volumes:
      - .:/code
      - .aws/credentials:/root/.aws/credentials
    working_dir: /code
    environment:
      # Terraform backend bucket creds
      - AWS_PROFILE=backend
      
      # Secrets for the appropriate Terraform workspace
      - TF_VAR_aws_access_key_id
      - TF_VAR_aws_secret_access_key
      - TF_VAR_cf_username
      - TF_VAR_cf_password
