---
name: apply

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  BUCKET: "${{ secrets.BUCKET }}"
  REGION: "${{ secrets.REGION }}"
  KEY: "ssb-tfstate"
  ENCRYPT: "true"

jobs:
  apply:

    name: apply
    runs-on: ubuntu-latest
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_cf_username: ${{ secrets.TF_VAR_cf_username }}
      TF_VAR_cf_password: ${{ secrets.TF_VAR_cf_password }}
      TF_VAR_aws_access_key_id: ${{ secrets.TF_VAR_aws_access_key_id }}
      TF_VAR_aws_secret_access_key: ${{ secrets.TF_VAR_aws_secret_access_key }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prep applications
        run: |
          ./app-setup-solr.sh
          ./app-setup-smtp.sh
      - name: OpenTofu apply (production)
        uses: dflook/tofu-apply@v1
        with:
          path: .
          label: production
          workspace: default
          var_file: terraform.production.tfvars
          backend_config: >
            bucket=${{ env.BUCKET }},
            key=${{ env.KEY }},
            region=${{ env.REGION }},
            encrypt=${{ env.ENCRYPT }},
            access_key=${{ env.AWS_ACCESS_KEY_ID }},
            secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}
